/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>


void generate_interrupt()
{
	//when in unpriviledged mode the code running on the
	//processor cannot access these addresses

	//Software Trigger Interrupt Register
	uint32_t* pSTIR=(uint32_t*)0xE000EF00;

	//Interrupt Set-enable Registers
	uint32_t* pISER0=(uint32_t*)0xE000E100;

	//enable irq3 interrupt
	*pISER0|=(1<<3);

	//generating an interrupt from software for irq3
	*pSTIR=(3 & 0x1FF);
}

void change_access_level_unpriv(void)
{
	//read the control register
	asm volatile ("MRS R0, CONTROL");

	//modify
	asm volatile ("ORR R0,R0,#0x01");

	//write
	asm volatile ("MSR CONTROL,R0");
}

int main(void)
{
	printf("In thread mode: Before any interrupt\n");

	void (*fun_ptr)(void);

	//fun_ptr will contain the value of the addr of the acces_level func
	//fun_ptr=change_access_level_unpriv;

	//hardcoding the function address
	fun_ptr=(void*)0x08000204;

	//de referencing fun_ptr
	//the value pointed by fun_ptr is going to get loaded into the program counter
	fun_ptr();

	//the t bit of the pc must be set to 1 otherwise the processor will
	//try to execute an instruction from the ARM ISA
	//but arm cortex m4 only supports thumb ISA
	//so this results in a hard fault

	//change_access_level_unpriv();

	//generate_interrupt();

	printf("In thread mode: After interrupt\n");

    /* Loop forever */
	for(;;);
}

//interrupt causes this ISR to execute thus processor is in handler mode while
//executing this
void RTC_WKUP_IRQHandler(void){
	printf("In handler mode: ISR\n");
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	while(1);
}
