/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define TIM2_IRQ_NO      28
#define I2C1EV_IRQ_NO    31

uint32_t *pNVIC_ISERbase=(uint32_t*)0xE000E100;
uint32_t *pNVIC_IPRbase=(uint32_t*)0xE000E400;
uint32_t *pNVIC_ISPRbase=(uint32_t*)0XE000E200;

void config_priorityForIRQ(uint8_t irq_no, uint8_t priority)
{
	//1. Find out the iprn register
	uint8_t IPRn=irq_no/4;
	uint32_t *IPR_addr=pNVIC_IPRbase+IPRn;
	IPRn=irq_no%4; //modulo returns the remainder of the division

	//2. Amount to left shift
	uint32_t Left_shift_value=IPRn*8;

	//3. Configure the priority
	*IPR_addr&=~(0xFF<<Left_shift_value); //clearing the bits prior to setting the priority
	*IPR_addr|=(priority<<Left_shift_value);
}

int main(void)
{
	//1. config the prio for the peripherals
	config_priorityForIRQ(TIM2_IRQ_NO, 0x80); //16 priority values are available for nucleo f446re
	config_priorityForIRQ(I2C1EV_IRQ_NO, 0x70); //this is due to 4 bits being avail to be modified IPR reg

	//2. Set the interrupt pending bit in NVIC PR
	*pNVIC_ISPRbase|=(1<<TIM2_IRQ_NO);

	//3. Enable the irqs in NVIC ISER
	*pNVIC_ISERbase|=(1<<I2C1EV_IRQ_NO);
	*pNVIC_ISERbase|=(1<<TIM2_IRQ_NO);

	for(;;);
}

void TIM2_IRQHandler(void)
{
	printf("Inside TIM2 IRQ Handler\n");
	*pNVIC_ISPRbase|=(1<<I2C1EV_IRQ_NO);
	while(1);
}

void I2C1_EV_IRQHandler(void)
{
	printf("Inside I2C1EV IRQ Handler\n");
}
