/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "led.h"

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t tick_hz);
void init_scheduler_stack(uint32_t scheduler_top_of_stack);
void init_task_stack(void);
void switch_sp_to_psp(void);
void enable_processor_faults(void);

void unblock_tasks(void);
void update_global_tick_count(void);
void schedule(void);

uint32_t get_psp_value(void);
void save_psp_value(uint32_t current_psp_value);

void task_delay(uint32_t tick_count);

uint32_t g_tick_count=0;

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	init_task_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

void idle_task(void)
{
	for(;;);
}

void task1_handler(void)
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler(void)
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task3_handler(void)
{
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void task4_handler(void)
{
	while(1)
	{
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t* pSRVR=(uint32_t*)0xE000E014; //SysTick Reload Value Register
	uint32_t* pSCSR=(uint32_t*)0xE000E010; //SysTick Control and Status Register

	uint32_t count_value=(SYSTICK_TIM_CLK/TICK_HZ)-1;

	//clear the value of svr
	*pSRVR&=~(0x00FFFFFFFF);

	//load the value into svr
	*pSRVR|=(count_value);

	//enable SysTick exception request
	*pSCSR|=(1<<1);

	//using the internal clock
	*pSCSR|=(1<<2);

	//enable the systick
	*pSCSR|=(1<<0); //Enables the counter
}

__attribute__ ((naked)) void init_scheduler_stack(uint32_t scheduler_top_of_stack)
{
	asm volatile("MSR MSP,%0"::"r"(scheduler_top_of_stack));
	asm volatile("BX LR");
}

void init_task_stack(void)
{
	for(uint8_t i=0;i<MAX_TASKS;i++)
	{
		user_tasks[i].current_state=TASK_READY_STATE;
	}

	user_tasks[0].psp_value=IDLE_STACK_START;
	user_tasks[1].psp_value=T1_STACK_START;
	user_tasks[2].psp_value=T2_STACK_START;
	user_tasks[3].psp_value=T3_STACK_START;
	user_tasks[4].psp_value=T4_STACK_START;

	user_tasks[0].task_handler=idle_task;
	user_tasks[1].task_handler=task1_handler;
	user_tasks[2].task_handler=task2_handler;
	user_tasks[3].task_handler=task3_handler;
	user_tasks[4].task_handler=task4_handler;

	uint32_t* pPSP;

	for(int i=0;i<MAX_TASKS;i++)
	{
		pPSP=(uint32_t*) user_tasks[i].psp_value;

		pPSP--;
		*pPSP=DUMMY_XPSR; //0x01000000

		pPSP--; //PC
		*pPSP=(uint32_t)user_tasks[i].task_handler;

		pPSP--; //LR
		*pPSP=0xFFFFFFFD;

		for(int j=0;j<13;j++) //this puts 0 into registers from r12 to r4
		{
			pPSP--;
			*pPSP=0;
		}

		user_tasks[i].psp_value=(uint32_t)pPSP;
	}
}

__attribute__ ((naked)) void switch_sp_to_psp(void)
{
	//1. Initialise the psp with task1 stack start address
	//get the psp for the current task
	asm volatile("PUSH {LR}"); //preserve lr which connects back to main()
	asm volatile("BL get_psp_value");
	asm volatile("MSR PSP,R0"); //init psp
	asm volatile("POP {LR}");

	//2. Change sp to psp using CONTROL register
	asm volatile("MOV R0,#0x02");
	asm volatile("MSR CONTROL,R0");
	asm volatile("BX LR");
}

void enable_processor_faults(void)
{
	uint32_t *pSHCRS=(uint32_t*)0xE000ED24; //System Handler Control and State Register address

	*pSHCRS|=(1<<16); //mem manage fault enabled
	*pSHCRS|=(1<<17); //bus fault enabled
	*pSHCRS|=(1<<18); //usage fault enabled
}

__attribute__ ((naked)) void PendSV_Handler(void)
{
	//Note: all of this code was in systick handler before
	/*Save the context of the current task*/
	//1. Get current running tasks's PSP value
	asm volatile("MRS R0,PSP");

	//2. Using that PSP value store SF2 (r4 to r11)
	asm volatile("STMDB R0!,{R4-R11}");

	asm volatile("PUSH {LR}"); //saves lr because it gets modified with the upcoming intructions

	//3. Save the current value of PSP
	asm volatile("BL save_psp_value");

	/*Retrieve the context of next task*/

	//1. Decide the next task to run
	asm volatile("BL update_next_task");

	//2. Get its past PSP value
	asm volatile("BL get_psp_value");

	//3. Using that PSP value retrieve SF2 (R4 to R11)
	asm volatile("LDMIA R0!,{R4-R11}");

	//4. Update PSP and exit
	asm volatile("MSR PSP,R0");

	//Lr is retrieved
	asm volatile("POP {LR}");

	asm volatile("BX LR");
}

void SysTick_Handler(void)
{
	update_global_tick_count();
	unblock_tasks();

	//Pend the pendsv exception
	uint32_t* pICSR=(uint32_t*)0xE000ED04;  //Interrupt Control and State Register

	*pICSR|=(1<<28);
}

void unblock_tasks(void)
{
	for(int i = 1;i<MAX_TASKS;i++)
	{
		if(user_tasks[i].current_state!=TASK_READY_STATE)
		{
			if(user_tasks[i].block_count==g_tick_count)
				user_tasks[i].current_state=TASK_READY_STATE;
		}
	}
}

void update_global_tick_count(void)
{
	g_tick_count++;
}

void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value=current_psp_value;
}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

void task_delay(uint32_t tick_count)
{
	//diasble interrupts
	INTERRUPT_DISABLE();

	if(current_task) //checks if current task is idle task
	{
		user_tasks[current_task].block_count=g_tick_count+tick_count;
		user_tasks[current_task].current_state=TASK_BLOCKED_STATE;
		schedule();
	}

	//enable interrupts
	INTERRUPT_ENABLE();

	//shared global var user_tasks is used by bth thread mode code and handler mode code
	//to avoid race condition interrupts are disabled and then enabled after the
	//required operations are done
}

void schedule(void)
{
	//Pend the pendsv exception
	uint32_t* pICSR=(uint32_t*)0xE000ED04;  //Interrupt Control and State Register

	*pICSR|=(1<<28);
}

void update_next_task(void)
{
	int state=TASK_BLOCKED_STATE;

	for(int i=0; i<(MAX_TASKS); i++)
	{
		current_task++;
		current_task%=MAX_TASKS;
		state=user_tasks[current_task].current_state;
		if((state==TASK_READY_STATE)&&(current_task!=0))
			break;
	}

	if(state!=TASK_READY_STATE)
		current_task=0;
}

void HardFault_Handler(void)
{
	printf("Exception: Hard Fault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception: Mem manage fault\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception: Bus Fault\n");
	while(1);
}

void UsageFault_Handler(void)
{
	printf("Exception: Usage Fault\n");
	while(1);
}
