/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define USART3_IRQ_NO 39

int main(void)
{
	//1. Manually pend the pending bit for the USART3 IRQ nuber in NVIC
	uint32_t *pISPR1=(uint32_t*)0XE000E204;

	*pISPR1|=(1<<USART3_IRQ_NO % 32);

	//2. Enable the ISART3 IRQ number in NVIC
	uint32_t *pISER1=(uint32_t*)0xE000E104;

	*pISER1|=(1<<USART3_IRQ_NO % 32);
	for(;;);
}

void USART3_IRQHandler(void)
{
	printf("In USART3 IRQ Handler\n");
}
