/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	asm("SVC #69");

	uint32_t data;

	asm volatile("MOV %0,r0":"=r"(data)::);

	printf("In main\n");

	//register uint32_t data asm("r0");

	printf("data = %ld\n",data);

	for(;;);
}

__attribute__ ((naked)) void SVC_Handler(void)
{
	//this extracted value of the msp is the
	//base addr of the stack frame which got saved during
	//the exception entry from thread mode to the handler mode
	asm("MRS r0,MSP");
	asm("B SVC_Handler_c");
	//value of r0 will be captured in the variable pBaseStackFrame
	//content of r0 becomes the argument 1 for the callee (the func being called)
}

void SVC_Handler_c(uint32_t *pBaseStackFrame)
{
	printf("In SVC Handler\n");
	uint8_t *pReturnAddress=(uint8_t*)*(pBaseStackFrame+6);

	//1. Get msp and addr being pointed by pc
	printf("MSP = %p\n",pBaseStackFrame);
	//printf("Value of PC = %lx\n",*(pBaseStackFrame+6));

	//2. Decrement the rerurn addr by 2 to point to the
	//opcode of the SVC instruction in the program memory
	printf("Return Address = %p\n",pReturnAddress);
	pReturnAddress-=2;

	//3. Extract the SVC number (LSB of the opcode)
	uint8_t svc_number=*pReturnAddress;

	printf("SVC number is: %d\n",svc_number);

	*pBaseStackFrame=svc_number-2;
}
