/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void SVC_Handle_c(uint32_t *pBaseStackFrame);

int32_t div_numbers(int32_t x, int32_t y);
int32_t mul_numbers(int32_t x, int32_t y);
int32_t add_numbers(int32_t x, int32_t y);
int32_t sub_numbers(int32_t x, int32_t y);

int main(void)
{
    int32_t res;

    res = add_numbers(40, -90);
    printf("Add result = %ld\n",res);

    res = sub_numbers(25,150);
    printf("Sub result = %ld\n",res);

    res = mul_numbers(374,890);
    printf("Mul result = %ld\n", res);

    res = div_numbers(67,-3);
    printf("Div result = %ld\n",res);

    for(;;);
}


__attribute__( ( naked ) ) void SVC_Handler( void )
{
    __asm("MRS r0,MSP");
    __asm( "B SVC_Handler_c");
}


void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	int32_t arg0, arg1, res;

    printf("Inside SVC handler\n");

    uint8_t *pReturnAddress = (uint8_t*)pBaseOfStackFrame[6];

    //2. decrement the return address by 2 to point to
    //opcode of the SVC instruction in the program memory
    pReturnAddress-=2;

    //3. extract the SVC number (LSByte of the opcode)
    uint8_t svc_number = *pReturnAddress;
    printf("SVC number = %d\n",svc_number);

    arg0=pBaseOfStackFrame[0];
    arg1=pBaseOfStackFrame[1];


/*SVC number signifies the type of operation , decode it */
    switch(svc_number)
    {
    case 36:
    	res=arg0+arg1;
        break;
    case 37:
    	res=arg0-arg1;
        break;
    case 38:
    	res=arg0*arg1;
        break;
    case 39:
    	res=arg0/arg1;
        break;
    default:
        printf("invalid svc code\n");
    }

/*store the result back to stack frame at R0's position */
    pBaseOfStackFrame[0]=res;
}

int32_t add_numbers(int32_t x, int32_t y)
{
    int32_t res;
    asm volatile("SVC #36");
    asm volatile("MOV %0,R0": "=r"(res) ::);
    return res;
}


int32_t sub_numbers(int32_t x, int32_t y)
{
    int32_t res;
    asm volatile("SVC #37");
    asm volatile("MOV %0,R0": "=r"(res) ::);
    return res;
}

int32_t mul_numbers(int32_t x, int32_t y)
{
    int32_t res;
    asm volatile("SVC #38");
    asm volatile("MOV %0,R0": "=r"(res) ::);
    return res;
}

int32_t div_numbers(int32_t x, int32_t y)
{
    int32_t res;
    asm volatile("SVC #39");
    asm volatile("MOV %0,R0": "=r"(res) ::);
    return res;
}
