/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
/* inline assembly syntax
  __asm volatile (code : output operand list : input operand list : clobber list);

- code part is always written in double quotes
*/
int main(void)
{
	//load r1 with following addr
	__asm volatile("LDR R1,=#0x20001000");

	//load r2 with following addr
	__asm volatile("LDR R2,=#0x20001004");

	//load value from r1 into r0
	__asm volatile("LDR R0,[R1]");

	//load value from r2 into r1
	__asm volatile("LDR R1,[R2]");

	//adding val in r0 and r1 and storing them into r0
	__asm volatile("ADD R0,R0,R1");

	//store val of r0 into r2
	__asm volatile("STR R0,[R2]");

	int val=50;
	//%0 signifies the 1st operand in this case val
	//more input operands can be added by giving a comma after val
	//r tells the compiler to use registers for data manipulation
	__asm volatile("MOV R0,%0": :"r"(val));

	//using immediate value skips the register being used
	__asm volatile("MOV R0,%0": :"i"(0x51));

	//in this case the value 0x50 is moved into a reg and then the reg is used to shift
	//value to r0
	__asm volatile("MOV R0,%0": :"r"(0x53));

	uint32_t control_reg;
	//=r modifier suggests the compiler that this a write only operand
	//MRS is Move from Special Register to general register
	//MSR is Move from general register to Special Register
	asm volatile("MRS %0,CONTROL":"=r"(control_reg));

	int var1=10, var2;
	//move value in var1 to var2
	asm volatile("MOV %0,%1":"=r"(var2):"r"(var1));

	int p1, *p2;
	p2=(int*)0x20000008;
	//load val of p2 (pointer) into p1
	//for ldr instruction the source is specified like this [source]
	asm volatile("LDR %0,[%1]":"=r"(p1):"r"(p2));

    /* Loop forever */
	for(;;);
}
