/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ALIAS_BASE_ADDR     0x22000000U
#define BITBAND_BASE_ADDR   0x20000000U


int main(void)
{
	uint8_t *ptr=(uint8_t*)0x20000200;

	//updating value to 0xff
	*ptr=0xff;

	//normal method
	//clearing 7th bit pos
	*ptr&=~(1<<7);

	//bit band method
	//resetting val
	*ptr=0xff;
	uint8_t *alias_address=(uint8_t*)(ALIAS_BASE_ADDR+(32*(0x20000200-BITBAND_BASE_ADDR))+7*4);

	//clearing the 7th bit of 0x20000200
	*alias_address=0;

	for(;;);
}
