/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>


void generate_interrupt()
{
	//Software Trigger Interrupt Register
	uint32_t* pSTIR=(uint32_t*)0xE000EF00;

	//Interrupt Set-enable Registers
	uint32_t* pISER0=(uint32_t*)0xE000E100;

	//enable irq3 interrupt
	*pISER0|=(1<<3);

	//generating an interrupt from software for irq3
	*pSTIR=(3 & 0x1FF);
}


int main(void)
{
	printf("In thread mode: Before any interrupt\n");

	generate_interrupt();

	printf("In thread mode: After interrupt\n");

    /* Loop forever */
	for(;;);
}

//interrupt causes this ISR to execute thus processor is in handler mode while
//executing this
void RTC_WKUP_IRQHandler(void){
	printf("In handler mode: ISR\n");
}
